[project]
name = "rag-against-the-machine"
version = "0.1.0"
description = "Will you answer my questions?"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "huggingface-hub>=1.31.0",
    "pydantic>=2.13.5",
    "torch>=2.14.0",
    "tqdm>=4.70.0",
    "transformers>=5.17.0",
]
